#include <Arduino.h>


#define RPWM_ESQUERDO_FRENTE 1
#define LPWM_ESQUERDO_FRENTE 3
#define L_EN_ESQUERDO_FRENTE 23
#define CANAL_RPWM_ESQUERDO_FRENTE 0
#define CANAL_LPWM_ESQUERDO_FRENTE 1

#define RPWM_ESQUERDO_TRAS 21
#define LPWM_ESQUERDO_TRAS 19
#define L_EN_ESQUERDO_TRAS 22
#define CANAL_RPWM_ESQUERDO_TRAS 2
#define CANAL_LPWM_ESQUERDO_TRAS 3


#define RPWM_DIREITO_TRAS 13
#define LPWM_DIREITO_TRAS 12
#define L_EN_DIREITO_TRAS 25 
#define CANAL_RPWM_DIREITO_TRAS 4
#define CANAL_LPWM_DIREITO_TRAS 5


#define RPWM_DIREITO_FRENTE 27
#define LPWM_DIREITO_FRENTE 14
#define L_EN_DIREITO_FRENTE 26 
#define CANAL_RPWM_DIREITO_FRENTE 6
#define CANAL_LPWM_DIREITO_FRENTE 7

void setup() {
  // Configuração dos pinos de saída
  pinMode(RPWM_DIREITO_FRENTE, OUTPUT);
  pinMode(LPWM_DIREITO_FRENTE, OUTPUT);
  pinMode(L_EN_DIREITO_FRENTE, OUTPUT);

  pinMode(RPWM_DIREITO_TRAS, OUTPUT);
  pinMode(LPWM_DIREITO_TRAS, OUTPUT);
  pinMode(L_EN_DIREITO_TRAS, OUTPUT);

  pinMode(RPWM_ESQUERDO_FRENTE, OUTPUT);
  pinMode(LPWM_ESQUERDO_FRENTE, OUTPUT);
  pinMode(L_EN_ESQUERDO_FRENTE, OUTPUT);

  pinMode(RPWM_ESQUERDO_TRAS, OUTPUT);
  pinMode(LPWM_ESQUERDO_TRAS, OUTPUT);
  pinMode(L_EN_ESQUERDO_TRAS, OUTPUT);


  ledcSetup(CANAL_RPWM_DIREITO_FRENTE,10000,8);
  ledcSetup(CANAL_LPWM_DIREITO_FRENTE,10000,8);
  ledcSetup(CANAL_RPWM_DIREITO_TRAS,10000,8);
  ledcSetup(CANAL_LPWM_DIREITO_TRAS,10000,8);


  ledcSetup(CANAL_RPWM_ESQUERDO_FRENTE,10000,8);
  ledcSetup(CANAL_LPWM_ESQUERDO_FRENTE,10000,8);
  ledcSetup(CANAL_RPWM_ESQUERDO_TRAS,10000,8);
  ledcSetup(CANAL_LPWM_ESQUERDO_TRAS,10000,8);

  ledcAttachPin(RPWM_DIREITO_FRENTE,CANAL_RPWM_DIREITO_FRENTE);
  ledcAttachPin(LPWM_DIREITO_FRENTE,CANAL_LPWM_DIREITO_FRENTE);

  ledcAttachPin(RPWM_DIREITO_TRAS,CANAL_RPWM_DIREITO_TRAS);
  ledcAttachPin(LPWM_DIREITO_TRAS,CANAL_LPWM_DIREITO_TRAS);

  ledcAttachPin(RPWM_ESQUERDO_FRENTE,CANAL_RPWM_ESQUERDO_FRENTE);
  ledcAttachPin(LPWM_ESQUERDO_FRENTE,CANAL_LPWM_ESQUERDO_FRENTE);

  ledcAttachPin(RPWM_ESQUERDO_TRAS,CANAL_RPWM_ESQUERDO_TRAS);
  ledcAttachPin(LPWM_ESQUERDO_TRAS,CANAL_LPWM_ESQUERDO_TRAS);
  
}

void loop() {
  ledcWrite(CANAL_RPWM_DIREITO_FRENTE,110);
  ledcWrite(CANAL_LPWM_DIREITO_FRENTE,0);
  digitalWrite(L_EN_DIREITO_FRENTE,1);

  ledcWrite(CANAL_RPWM_DIREITO_TRAS,110);
  ledcWrite(CANAL_LPWM_DIREITO_TRAS,0);
  digitalWrite(L_EN_DIREITO_TRAS,1);

  ledcWrite(CANAL_RPWM_ESQUERDO_FRENTE,110);
  ledcWrite(CANAL_LPWM_ESQUERDO_FRENTE,0);
  digitalWrite(L_EN_ESQUERDO_FRENTE,1);

  ledcWrite(CANAL_RPWM_ESQUERDO_TRAS,110);
  ledcWrite(CANAL_LPWM_ESQUERDO_TRAS,0);
  digitalWrite(L_EN_ESQUERDO_TRAS,1);

  // delay(2000);
  // ledcWrite(CANAL_RPWM_DIREITO_FRENTE,0);
  // ledcWrite(CANAL_LPWM_DIREITO_FRENTE,0);
  // digitalWrite(L_EN_DIREITO_FRENTE,1);

  // ledcWrite(CANAL_RPWM_DIREITO_TRAS,0);
  // ledcWrite(CANAL_LPWM_DIREITO_TRAS,0);
  // digitalWrite(L_EN_DIREITO_TRAS,1);

  // ledcWrite(CANAL_RPWM_ESQUERDO_FRENTE,0);
  // ledcWrite(CANAL_LPWM_ESQUERDO_FRENTE,0);
  // digitalWrite(L_EN_ESQUERDO_FRENTE,1);

  // ledcWrite(CANAL_RPWM_ESQUERDO_TRAS,0);
  // ledcWrite(CANAL_LPWM_ESQUERDO_TRAS,0);
  // digitalWrite(L_EN_ESQUERDO_TRAS,1);
  // delay(2000);


  // ledcWrite(CANAL_RPWM_DIREITO_FRENTE,0);
  // ledcWrite(CANAL_LPWM_DIREITO_FRENTE,110);
  // digitalWrite(L_EN_DIREITO_FRENTE,1);

  // ledcWrite(CANAL_RPWM_DIREITO_TRAS,0);
  // ledcWrite(CANAL_LPWM_DIREITO_TRAS,110);
  // digitalWrite(L_EN_DIREITO_TRAS,1);

  // ledcWrite(CANAL_RPWM_ESQUERDO_FRENTE,0);
  // ledcWrite(CANAL_LPWM_ESQUERDO_FRENTE,110);
  // digitalWrite(L_EN_ESQUERDO_FRENTE,1);

  // ledcWrite(CANAL_RPWM_ESQUERDO_TRAS,0);
  // ledcWrite(CANAL_LPWM_ESQUERDO_TRAS,110);
  // digitalWrite(L_EN_ESQUERDO_TRAS,1);

  // delay(2000);
  // ledcWrite(CANAL_RPWM_DIREITO_FRENTE,0);
  // ledcWrite(CANAL_LPWM_DIREITO_FRENTE,0);
  // digitalWrite(L_EN_DIREITO_FRENTE,1);

  // ledcWrite(CANAL_RPWM_DIREITO_TRAS,0);
  // ledcWrite(CANAL_LPWM_DIREITO_TRAS,0);
  // digitalWrite(L_EN_DIREITO_TRAS,1);

  // ledcWrite(CANAL_RPWM_ESQUERDO_FRENTE,0);
  // ledcWrite(CANAL_LPWM_ESQUERDO_FRENTE,0);
  // digitalWrite(L_EN_ESQUERDO_FRENTE,1);

  // ledcWrite(CANAL_RPWM_ESQUERDO_TRAS,0);
  // ledcWrite(CANAL_LPWM_ESQUERDO_TRAS,0);
  // digitalWrite(L_EN_ESQUERDO_TRAS,1);
  // delay(2000);


}
